name:                JentekDev
author:              Chris Jensen
maintainer:          cjj39@cam.ac.uk

default-extensions:
 - ApplicativeDo
 - BangPatterns
# - ContraintKinds
 - DataKinds
 - DefaultSignatures
 - DeriveFoldable
 - DeriveFunctor
 - DeriveGeneric
 - DeriveLift
 - DeriveTraversable
 - DerivingStrategies
 - EmptyCase
 - ExistentialQuantification
 - FlexibleContexts
 - FlexibleInstances
 - FunctionalDependencies
 - GADTs
 - GeneralizedNewtypeDeriving
 - InstanceSigs
 - KindSignatures
 - LambdaCase
 - MultiParamTypeClasses
 - MultiWayIf
 - NamedFieldPuns
 - OverloadedStrings
 - PatternSynonyms
 - RankNTypes
 - ScopedTypeVariables
 - StandaloneDeriving
 - TupleSections
 - TypeApplications
 - TypeFamilies
 - TypeFamilyDependencies
 - TypeOperators

dependencies:
 - base
 - hakyll
 - typelits-printf

library:
  source-dirs: lib/

executables:
  site-exe:
    main:         Site.hs
    source-dirs:  . 
    dependencies:
     - base
     - hakyll
     - JentekDev
