# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  site-build:
    docker:
      - image: cjen1/hakyll:4.12.5.1
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e4:06:c0:ec:11:78:f9:17:c8:f3:88:b7:58:fd:1e:85"
      - checkout
      - run: 
          name: Checkout submodule
          command: |
            git submodule update --init
            cd _site
            git checkout master
      - restore_cache:
          keys:
            - v1-stack-work-{{ checksum "package.yaml" }}
      - run:
          name: Build the static site generator executable
          command: stack build --install-ghc
      - save_cache:
          key: v1-stack-work-{{ checksum "package.yaml" }}
          paths:
            - ~/cjen1-github-io/.stack-work
            - ~/.stack
      - run:
          name: Build the site
          command: stack run build
      - run:
          name: Setup git config
          command: |
            git config --global user.email "cjj39@cam.ac.uk"
            git config --global user.name "Cjen1"
      - run:
          name: Git commit and push
          command: |
            cd _site
            git add --all 
            git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
            git push "$CIRCLE_REPOSITORY_URL" master

workflows:
  version: 2.1
  build:
    jobs:
      - site-build:
          filters:
            branches:
              only: src
